---
title: NFL Analytics - Feature Engineering
author: Juan Solorio
date: "`r format(Sys.time(),'%d %B, %Y')`"
output: bookdown::html_document2
---

```{r, set_work_directory, echo=FALSE}

setwd('C:/Users/Juan Solorio/Desktop/DataScience/Grad School/Classes/Data 598C/Data-598C-wi2020/')

```

```{r, load_data}
load('data_train_cleaned.Rdata')

head(data_train)

```

```{r, add-Season-week-Func, echo=FALSE}
add.week.of.season <- function(df_in) {
  #------------------------------------------------------------
  # Funtion takes in either data_train or data_test,
  # looks at the individual season and adds a week for each game
  # Returns a dataframe with same dimensions as df provided plus added 'Week' col
  #------------------------------------------------------------
  tempdf1 <- df_in[,]     #temporary df copying the df provided
  seasons <- unique(df_in$SeasonYear)     # getting the individual season in df
  tempdf1$Week <- NA      #adding in the 'Week' column to the temp df
  tempdf2 <- data.frame() #setting 2nd tempdf for appending through rbind
  
  #   3 level loop to go through seasons, days in season, and day in group 
  #   of 3 days composing the NFL week (Thu, Sun, Mon) 
  for(season in seasons){
    dfSeason <- tempdf1[tempdf1$SeasonYear == season,]
    dates <- unique(dfSeason$GameDate)
    week <- 1
    
    # NFL season is composed of 17 weeks, each of 3 different game days
    # Divided the number of game days by 3 to account for the 3 game days
    # added 1 to capture the last week of the season, as I pass 'n' as an int
    # to get the 3 day vector from dates
    for(n in 1:(length(dates)/3+1)){
      # contiditional to break the loop if we reach week 18
      if (n == 18) {
        break
      }
      # subtract 1 to reindex for the purpose of the sequence  of dates
      n <- n-1
      days <- c(dates[(3*n+1):(3*n+3)])
      days <- days[!is.na(days)]
      
      # Loop through the 3 indivual week days to give the correct week to each
      for(i in days){
        df1 <- tempdf1[tempdf1$GameDate == i,]
        df1$Week <- week
        tempdf2 <- rbind(tempdf2, df1)
      }
      week <- week +1
    }
  }
  return(tempdf2)
}

```

```{r, weeks_column_add}
# Passed 'data_train' df into add week function to get weeks column
data_train_week_added <- add.week.of.season(data_train)

# print the head to confirm we have the added column
head(data_train_week_added, n = 3)
```

```{r, add_playsuccess_yrdstotd}
data_train_playsuccess_add <- data_train_week_added[,]

data_train_playsuccess_add$PlaySuccess <- as.numeric(data_train_playsuccess_add$Yards > 0 | (data_train_playsuccess_add$DefenseTeam == as.character(data_train_playsuccess_add$PenaltyTeam) & !is.na(data_train_playsuccess_add$PenaltyTeam)))

data_train_yrstotd_add <- data_train_playsuccess_add[,]
data_train_yrstotd_add$YarsToTD <- 100 - as.numeric(data_train_yrstotd_add$YardLineFixed)

```

